name: Deploy Components to Mainnet
on:
  push:
    branches: [main]
jobs:
  deploy-mainnet:
    uses: NEARBuilders/bos-workspace/.github/workflows/deploy.yml@main
    with:
      bw-legacy: false
      deploy-env: "mainnet"
      app-name: "docs.bos-workspace.near"
      deploy-account-address: docs.bos-workspace.near
      signer-account-address: docs.bos-workspace.near
      signer-public-key: ed25519:ArU6AYi2z8AdgAomtJrX6dmxy3V3Lx5cH8wudkXTFmW4
    secrets:
      SIGNER_PRIVATE_KEY: ${{ secrets.SIGNER_PRIVATE_KEY }}
